# Generated by Django 4.2.2 on 2023-06-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
