# Generated by Django 3.0 on 2023-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230622_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=255),
        ),
    ]
